--proxy "socks5://127.0.0.1:10808"
--concurrent-fragments 6
--embed-metadata
#--console-title
--no-check-certificate
--limit-rate 5M
--impersonate "firefox"
--legacy-server-connect
--paths "temp:D:\00Temp\01Cache\MedHunt"
--paths "home:D:\00Temp\02MedHunt"
--skip-unavailable-fragments
#--fragment-retries 20
#--cookies "cookies.txt"
--verbose
--cookies-from-browser firefox
--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:148.0) Gecko/20100101 Firefox/148.0"
--add-header "Sec-Fetch-Dest: empty"
--add-header "Sec-Fetch-Mode: cors"
--add-header "Sec-Fetch-Site: cross-site"
--add-header "Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2"
--add-header "Accept-Encoding: gzip, deflate, br"